docs/data-sources/elasticsearch_security_user.md, docs/data-sources/elasticsearch_snapshot_repository.md, docs/index.md, docs/resources/elasticsearch_cluster_settings.md, docs/resources/elasticsearch_index_lifecycle.md, docs/resources/elasticsearch_index_template.md, docs/resources/elasticsearch_security_role.md, docs/resources/elasticsearch_security_user.md, docs/resources/elasticsearch_snapshot_lifecycle.md, docs/resources/elasticsearch_snapshot_repository.md, internal/clients/api_client.go, internal/provider/provider.go, internal/utils/utils.go
This is my attempt to implement an insecure option to disable TLS validation.
I believe I've also addressed the issues brought up in my other PR for the ca_file option.  
I'm a little unsure on my use of http.DefaultTransport.  After looking at the elasticsearch-go and elastic-transport-go source, it's my understanding that if no transport is set in elasticsearch.Config, then http.DefaultTransport is used.  
Feedback is certainly welcome. 
related https://github.com/elastic/terraform-provider-elasticstack/issues/34
=> add insecure option to disable TLS validation

docs/data-sources/elasticsearch_security_user.md, docs/data-sources/elasticsearch_snapshot_repository.md, docs/index.md, docs/resources/elasticsearch_cluster_settings.md, docs/resources/elasticsearch_index_lifecycle.md, docs/resources/elasticsearch_index_template.md, docs/resources/elasticsearch_security_role.md, docs/resources/elasticsearch_security_user.md, docs/resources/elasticsearch_snapshot_lifecycle.md, docs/resources/elasticsearch_snapshot_repository.md, internal/clients/api_client.go, internal/provider/provider.go, internal/utils/utils.go
allows connecting to an elasticsearch cluster using a custom certificate authority.
I know just enough go to get myself in trouble, but figured I would try to solve my own problem anyways. resolves #34 
It adds the "ca_file" parameter to the elasticstack provider.  If ca_file is set, the certificate is read and its contents are added to the CACert field in the elasticsearch.Config struct.
=> add "ca_file" option to the elasticstack provider

docs/guides/elasticstack-and-cloud.md, templates/guides/elasticstack-and-cloud.md.tmpl
Currently this title is missing which leaves empty `#` in the beginning of the file, see https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/guides/elasticstack-and-cloud
=> Added title in the cloud guide

docs/resources/elasticsearch_cluster_settings.md, docs/resources/elasticsearch_index.md, docs/resources/elasticsearch_index_lifecycle.md, docs/resources/elasticsearch_index_template.md, docs/resources/elasticsearch_security_role.md, docs/resources/elasticsearch_security_user.md, docs/resources/elasticsearch_snapshot_lifecycle.md, docs/resources/elasticsearch_snapshot_repository.md, internal/elasticsearch/cluster/settings.go, internal/elasticsearch/cluster/slm.go, internal/elasticsearch/cluster/snapshot_repository.go, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/index.go, internal/elasticsearch/index/template.go, internal/elasticsearch/security/role.go, internal/elasticsearch/security/user.go
We must explicitly define ID in the schema, to make sure it's rendered as read-only in the docs, since it should not be possible to change or set the id in the TF resource definition.
=> Make sure to define ID as rad-only/computed attribute

CHANGELOG.md, docs/resources/elasticsearch_index.md, examples/resources/elasticstack_elasticsearch_index/import.sh, internal/elasticsearch/index/index.go, templates/resources/elasticsearch_index.md.tmpl
Make sure we are able to import all the index settings. Also, after index is created we support only the settings, which are defined in the TF files. 
fix https://github.com/elastic/terraform-provider-elasticstack/issues/53
=> Support import of the index settings

CHANGELOG.md, docs/resources/elasticsearch_index_lifecycle.md, examples/resources/elasticstack_elasticsearch_index_lifecycle/resource.tf, internal/clients/index.go, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/ilm_test.go
Allocate action can contain `include`, `exclude` and `require` fields, which are JSON objects and must be handled appropriately.
fix https://github.com/elastic/terraform-provider-elasticstack/issues/59
=> Fix issue with `allocate` action for ILM

CHANGELOG.md, docs/resources/elasticsearch_security_user.md, internal/elasticsearch/security/user.go, internal/models/models.go
fix https://github.com/elastic/terraform-provider-elasticstack/issues/66
=> Send only set values to ES api

internal/clients/cluster.go, internal/clients/security.go
This PR fixes `nil pointer dereference`, reported in the linked issue for security user data source. 
fix: https://github.com/elastic/terraform-provider-elasticstack/issues/73
And also as proactive action, fixes the same potential bug for snapshot repositories data source
=> Data sources: return error if the requested resource not found

.ci/pipelines/acceptance.groovy, internal/elasticsearch/index/template.go, internal/elasticsearch/index/template_test.go
I'm trying to follow docs from https://www.jenkins.io/doc/book/pipeline/syntax/#declarative-matrix to create a matrix job to test this provider with different versions of the ES 
This is the initial PR and just adds 2 ES version `'8.0.0'` and `'7.15.1'`. I just want to make sure the job does what it's supposed to do and later I also plan to run different tests depending on the version major version `8.x` or `7.x` 
Looking great:
=> Convert CI job to the `matrix` one for acceptance testing

docs/resources/elasticsearch_index.md, internal/elasticsearch/index/index.go
Now the links include closing parenthesis and they are not working.
This PR fixes it by making it markdown link.
=> Fix invalid links in the document for index resource

.gitignore, CHANGELOG.md, docs/resources/elasticsearch_security_role.md, internal/elasticsearch/security/role.go, internal/elasticsearch/security/role_test.go, internal/models/models.go, main.tf
- Add allow_restricted_indices setting (identified as missing: https://github.com/elastic/terraform-provider-elasticstack/issues/125)
=> [ISSUE-125] Add allow_restricted_indices setting to security role

CHANGELOG.md, README.md, docs/data-sources/elasticsearch_security_user.md, docs/data-sources/elasticsearch_snapshot_repository.md, docs/index.md, docs/resources/elasticsearch_cluster_settings.md, docs/resources/elasticsearch_component_template.md, docs/resources/elasticsearch_data_stream.md, docs/resources/elasticsearch_index.md, docs/resources/elasticsearch_index_lifecycle.md, docs/resources/elasticsearch_index_template.md, docs/resources/elasticsearch_ingest_pipeline.md, docs/resources/elasticsearch_security_role.md, docs/resources/elasticsearch_security_user.md, docs/resources/elasticsearch_snapshot_lifecycle.md, docs/resources/elasticsearch_snapshot_repository.md, examples/provider/provider-apikey.tf, internal/acctest/acctest.go, internal/clients/api_client.go, internal/provider/provider.go, internal/utils/utils.go, templates/index.md.tmpl
The https://pkg.go.dev/github.com/elastic/go-elasticsearch/v8 client supports both username/password auth, as well as API Key. However the Terraform provider currently only supports username/password. I've made a quick change to allow the API Key to be specified instead. It is mainly just a schema change, and then the API client config needs to use the value from the provider schema.
I've tested this with one of my local projects, and it successfully created the user and role resources using only the API Key. Also the acceptance tests pass:
```
TF_ACC=1 go test -v ./... -count 1 -parallel 10  -timeout 120m
?       github.com/elastic/terraform-provider-elasticstack      [no test files]
?       github.com/elastic/terraform-provider-elasticstack/internal/acctest     [no test files]
? …
```
=> Add api key option

CHANGELOG.md, internal/clients/api_client.go, internal/clients/cluster.go, internal/clients/index.go, internal/clients/security.go, internal/elasticsearch/cluster/settings.go, internal/elasticsearch/cluster/slm.go, internal/elasticsearch/cluster/snapshot_repository.go, internal/elasticsearch/cluster/snapshot_repository_data_source.go, internal/elasticsearch/index/component_template.go, internal/elasticsearch/index/data_stream.go, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/index.go, internal/elasticsearch/index/template.go, internal/elasticsearch/ingest/pipeline.go, internal/elasticsearch/security/role.go, internal/elasticsearch/security/user.go, internal/elasticsearch/security/user_data_source.go
This PR refactors methods to pass context to api calls to be context aware.
=> Pass context to api calls

go.mod, internal/clients/api_client.go, internal/clients/cluster.go, internal/clients/debug.go, internal/clients/index.go, internal/clients/security.go, internal/elasticsearch/index/data_stream.go, internal/elasticsearch/index/index.go
This PR introduces automatic debug log dump of each req/res instead of manually adding trace logs.
Also `log.Printf` is [legacy](https://www.terraform.io/plugin/log/writing) now, so it's replaced with `tflog`.
It would make it easier to debug an issue.
(e.g. below is the issue in a provider which uses the same debug transport.
https://github.com/k-yomo/terraform-provider-algolia/issues/79
=> Debug log each req/res of API call

CHANGELOG.md, internal/acctest/acctest.go, internal/elasticsearch/security/user.go, internal/elasticsearch/security/user_test.go, provider/provider.go
- Only update `password` and `password_hash` when the value has changed in the Terraform configuration (identified by: https://github.com/elastic/terraform-provider-elasticstack/issues/127) (required behaviour in issue is backed up by API docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html)
=> [ISSUE-127] Only change password and password_hash when value changes

CHANGELOG.md, docs/index.md, docs/resources/elasticsearch_index.md, internal/elasticsearch/index/index.go, internal/elasticsearch/index/index_test.go
Resolves #124 
As mentioned in #124, current `settings` field's usability is low due to the limitation of type(string object with no nest) and causing issues like #108 and #119 .
This PR introduces individual fields to improve usability by allowing json for some fields like `analyzer` and robustness by having strict key and value type for each setting key.
- This PR is backward compatible, so the `settings` field is deprecated but still usable until we remove it (in  next major version update?).
- The schema is pretty much same as `phillbaker/terraform-provider-elasticsearch`'s [index resource](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/es/resource_elasticsearch_index.go).  So it also makes it easier to migrate from …
=> Improve index resource usability by adding individual setting fields

docs/resources/elasticsearch_security_role.md, examples/resources/elasticstack_elasticsearch_security_role/import.sh
This PR fixes the missing resource id in the role resource import example.
https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/elasticsearch_security_role#import
=> Fix role imoprt example

CHANGELOG.md, main.go
This PR refactors the main function not to use deprecated `plugin.Debug`.
The change is pretty much the same as the below PR.
https://github.com/hashicorp/terraform-provider-scaffolding/pull/104/files
=> Refactor deprecated debug method with simplified one

CHANGELOG.md
Updating to ensure link works within Changelog for v0.4.0 and unreleased
=> update changelog with tag comparison following v0.4.0 release

.github/workflows/test.yml, Makefile, docs/resources/elasticsearch_index.md, examples/resources/elasticstack_elasticsearch_index/resource.tf
Resolves #168
Add Github action workflow which includes
- build
- lint (misspell golangci-lint fmt-check docs-check)
- acctest
- matrix is used to replace jenkins, but if we keep jenkins, then just specifying the latest version might be enough.
example run is below
https://github.com/k-yomo/terraform-provider-elasticstack/actions/runs/3342618068
=> Add Github actions workflow

CHANGELOG.md, internal/elasticsearch/cluster/settings.go, internal/elasticsearch/cluster/slm.go, internal/elasticsearch/cluster/snapshot_repository.go, internal/elasticsearch/index/component_template.go, internal/elasticsearch/index/data_stream.go, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/index.go, internal/elasticsearch/index/template.go, internal/elasticsearch/ingest/pipeline.go, internal/elasticsearch/security/role.go, internal/elasticsearch/security/user.go
Unsetting id after deleting resource is taken care by SDK.  This PR removes unnecessary id unsetting on delete.
https://github.com/hashicorp/terraform-plugin-sdk/blob/156a6387060960ab65370f6488b95500e577ae49/helper/schema/resource.go#L813-L814
=> Remove unnecessary unsetting id on delete

.ci/Makefile.ci, .github/workflows/test.yml, Makefile
I just found that build takes time because of running lint too.
This PR remove lint from build and make CI faster.
https://github.com/elastic/terraform-provider-elasticstack/actions/runs/3343380392/jobs/5536539164
=> Remove lint from build and test

internal/clients/logstash.go, internal/clients/security.go
It's possible that the response is nil when error is not nil.
This PR fixes the error handling that might cause panic with null pointer exception.
`res.IsError()` is still handled in the following `utils.CheckError(res, "error message")`
=> Fix error handling

CHANGELOG.md, docs/resources/elasticsearch_index.md, docs/resources/elasticsearch_index_lifecycle.md, examples/resources/elasticstack_elasticsearch_index/resource.tf, examples/resources/elasticstack_elasticsearch_index_lifecycle/resource.tf, internal/clients/api_client.go, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/ilm_test.go, internal/elasticsearch/index/index_test.go, internal/elasticsearch/security/user_test.go
- Fix small typo on variable name (housekeeping)
- Add total_shards_per_node setting (identified as missing: https://github.com/elastic/terraform-provider-elasticstack/issues/112) 
Fixes #112
=> [ISSUE-112] Add total_shards_per_node setting to allocate in ILM

CHANGELOG.md, docs/resources/elasticsearch_index.md, internal/elasticsearch/index/index.go, internal/elasticsearch/index/index_test.go
=> Add 'unassigned_node_left_delayed_timeout' field to index resource

internal/clients/elasticsearch/cluster.go, internal/elasticsearch/cluster/script.go, internal/elasticsearch/cluster/settings.go, internal/elasticsearch/cluster/slm.go, internal/elasticsearch/cluster/snapshot_repository.go, internal/elasticsearch/cluster/snapshot_repository_data_source.go
Related to https://github.com/elastic/terraform-provider-elasticstack/issues/100
As it stands the ApiClient struct is becoming cluttered and massive. Adding Kibana will only make this worse. First step in breaking up the API access methods.
=> Refactor elasticsearch cluster client methods

docs/data-sources/elasticsearch_security_role.md, docs/data-sources/elasticsearch_security_role_mapping.md, docs/data-sources/elasticsearch_security_user.md, docs/data-sources/elasticsearch_snapshot_repository.md, docs/index.md, docs/resources/elasticsearch_cluster_settings.md, docs/resources/elasticsearch_component_template.md, docs/resources/elasticsearch_data_stream.md, docs/resources/elasticsearch_index.md, docs/resources/elasticsearch_index_lifecycle.md, docs/resources/elasticsearch_index_template.md, docs/resources/elasticsearch_ingest_pipeline.md, docs/resources/elasticsearch_logstash_pipeline.md, docs/resources/elasticsearch_script.md, docs/resources/elasticsearch_security_api_key.md, docs/resources/elasticsearch_security_role.md, docs/resources/elasticsearch_security_role_mapping.md, docs/resources/elasticsearch_security_system_user.md, docs/resources/elasticsearch_security_user.md, docs/resources/elasticsearch_snapshot_lifecycle.md, docs/resources/elasticsearch_snapshot_repository.md, internal/schema/connection.go, internal/utils/utils.go, provider/provider.go
First part of [#203](https://github.com/elastic/terraform-provider-elasticstack/issues/203).
=> DRY up ES connection

internal/elasticsearch/security/user_data_source.go
Refactor `dataSourceSecurityUserRead` to use `resourceSecurityUserRead` to simplify the code.
=> Refactor dataSourceSecurityUserRead

docs/guides/elasticstack-and-cloud.md, examples/cloud/deployment.tf, examples/cloud/provider.tf, templates/guides/elasticstack-and-cloud.md.tmpl
This property should probably be a last resort. It's not available during an import and there's just better ways to handle this. 
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/114
=> Configure the stack provider with Cloud credentials rather than elasticsearch_connection

CHANGELOG.md, internal/elasticsearch/cluster/slm.go, internal/elasticsearch/cluster/slm_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/109
`GetOk` returns `ok=false` for zero valued attributes, so this option was never being set in the policy and the default (true) was applied.
=> Apply zeroish values in SLM policies

.github/workflows/test.yml
Added these versions to CI and remove old 3 versions. 
- `8.3.3`
- `8.4.3`
- `8.5.3`
https://www.elastic.co/guide/en/elasticsearch/reference/current/es-release-notes.html
📝 Need to update `Status checks` too
=> Add recent elasticsearch versions to CI

CHANGELOG.md, docs/resources/elasticsearch_index.md, internal/elasticsearch/index/index.go, internal/elasticsearch/index/index_test.go
Resolves #227 
This PR changes not to recreate when field is removed in a new mapping (= mapping defined in terraform), not to cause recreate mainly for dynamically added fields.
Ignoring field removal is the default behaviour of Elasticsearch, so it'll be aligned wit Elasticsearch too.
📝 This PR is branched from https://github.com/elastic/terraform-provider-elasticstack/pull/231
=> Don't recreate when field is removed

internal/clients/api_client.go, internal/models/models.go
Cluster info is retrieved for every resource to use cluster uuid now.  
This PR caches cluster info to be able to speed up it.
=> Cache cluster info to speed up application

CHANGELOG.md, docs/resources/elasticsearch_index.md, internal/clients/elasticsearch/index.go, internal/elasticsearch/index/index.go, internal/elasticsearch/index/index_test.go, internal/models/models.go, internal/utils/validation.go, internal/utils/validation_test.go
Resolve #242 
This PR adds support for the following query params that we can set for index creation.
- `include_type_name`
- `wait_for_active_shards`
- `master_timeout`
- `timeout`
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/indices-create-index.html#indices-create-api-query-params
📝 `master_timeout` and `timeout` are used in the other apis, so it might be better to make it reusable.
https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-put-lifecycle.html#ilm-put-lifecycle-query-params
=> Add support for index creation query params

.github/workflows/test.yml
This PR adds recently released [v8.6.0](https://github.com/elastic/elasticsearch/releases/tag/v8.6.0) to CI.
=> Add v8.6.0 to CI

CHANGELOG.md, docs/resources/elasticsearch_index_lifecycle.md, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/ilm_test.go, internal/versionutils/testutils.go
Resolves #247 
This PR adds `min_*` fields to rollover which is released in [8.4.0](https://www.elastic.co/guide/en/elasticsearch///reference/master/release-notes-8.4.0.html).
https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-rollover.html
=> Add min_* conditions to rollover

Makefile
`docker-testacc` was removed when we migrated CI to GitHub Actions, but it's useful to run acceptance tests in local.
It's also still in the README.
https://github.com/elastic/terraform-provider-elasticstack#developing-the-provider
=> Re-add `docker-testacc` command

internal/clients/api_client.go, internal/clients/debug.go
Resolves #258 
`httputil.DumpRequestOut` is actually executing dummy [RondTrip](https://github.com/golang/go/blob/733ba921875ea11088f1f447cbca418f651aae5c/src/net/http/httputil/dump.go#L146) and it causes following error since the schema and host is not set at the point.
`request dump error: &errors.errorString{s:"unsupported protocol scheme \"\""}`
This PR changes the method to use `httputil.DumpRequest` which can work with an incomplete url.
```
2023-01-25T01:36:36.976+0900 [DEBUG] provider.terraform-provider-elasticstack: elasticsearch API Request Details:
---[ REQUEST ]---------------------------------------
GET /products?flat_settings=true HTTP/1.1
-----------------------------------------------------: @module=elasticstack tf_mux_provider=*schema.GRPCProviderServer …
```
=> Fix request dump debug log

.github/workflows/test.yml
This PR removes versions which reached EOL, and add `8.7.0` in CI.
- https://www.elastic.co/support/eol
- https://www.elastic.co/guide/en/elasticsearch/reference/current/es-release-notes.html
=> Update Elasticsearch versions in CI

internal/clients/kibana/alerting.go
When creating a Kibana alerting rule with multiple actions (using the unreleased version of the provider), there is a bug at the point of copying the resource's action into the api struct `alerting.ActionsInner`.
For instance:
```terraform
resource "elasticstack_kibana_alerting_rule" "my_kibana_alerting_rule" {
name         = "tf - my kibana alerting rule"
consumer     = "alerts"
notify_when  = "onActiveAlert"
rule_type_id = "logs.alert.document.count"
interval     = "1m"
enabled      = true
tags         = ["terraform""]
params = jsonencode({
// some params here
})
actions {
id    = "UUID-1-Connector"
group = "logs.threshold.fired"
params = jsonencode({
// some params here
})
}
actions {
id    =  "UUID-2-Connector"
group = "logs.threshold.fired"
params = jsonencode({
// some params here …
```
=> Fix mapping Kibana alerting rule actions to api alerting.ActionInner

CHANGELOG.md, docs/resources/elasticsearch_snapshot_lifecycle.md, internal/elasticsearch/cluster/slm.go, internal/elasticsearch/cluster/slm_test.go
Resolves #325 by changing type of `indices` field to `List`.
=> Guarantee indices order in SLM

CHANGELOG.md, docs/resources/elasticsearch_watch.md, docs/resources/kibana_space.md, examples/resources/elasticstack_elasticsearch_watch/resource.tf, examples/resources/elasticstack_kibana_space/resource.tf, internal/elasticsearch/watcher/watch.go, internal/elasticsearch/watcher/watch_test.go, internal/kibana/space.go, internal/kibana/space_test.go, internal/models/models.go
- Add missing `transform` field to watcher resource (https://github.com/elastic/terraform-provider-elasticstack/issues/337)
- Add upgrade instructions surrounding `logstash_pipeline` breaking change (https://github.com/elastic/terraform-provider-elasticstack/issues/334)
- Fix error presented by incorrect handling of `disabled_features` field in `elasticstack_kibana_space` resource (https://github.com/elastic/terraform-provider-elasticstack/issues/336)
=> Add patches following version bump

CHANGELOG.md, docs/resources/fleet_agent_policy.md, internal/fleet/agent_policy_resource.go, internal/fleet/agent_policy_resource_test.go
Add a flag which can skip the attempt to remove the Agent Policy from Fleet using the API. This is useful in cases where an Agent is not managed directly by Terraform and it is not safe to remove the policy, as there may still be agents assigned to the policy.
=> Add skip_destory flag for Fleet Agent Policies

internal/elasticsearch/cluster/slm.go, internal/elasticsearch/cluster/slm_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/360
Does what it says on the tin. Importing an SLM policy currently doesn't set the name property, resulting in the policy being recreated on the next apply.
=> Set the policy name when importing an SLM policy

docs/resources/kibana_action_connector.md, docs/resources/kibana_alerting_rule.md, internal/kibana/connector.go, templates/resources/kibana_action_connector.md.tmpl, templates/resources/kibana_alerting_rule.md.tmpl
Relates to https://github.com/elastic/kibana/issues/158647
This PR updates the links in https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/kibana_action_connector and https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/kibana_alerting_rule to use the "current" version of the documentation.
=> [DOCS] Change rule and connector links to current

docs/guides/elasticstack-kibana-rule.md, docs/resources/kibana_alerting_rule.md, examples/resources/elasticstack_kibana_alerting_rule/resource-index-rule.tf, internal/kibana/alerting.go
This PR adds a second action to the rule in the alerting rule guide.
It also edits the kibana alerting rule descriptions to align with changes made in the appropriate open API specification. In particular, it's important to clarify that `actions` is not an array and that `notify_when` and `throttle` are rule-level values, since the resource doesn't yet support action frequency settings per https://github.com/elastic/terraform-provider-elasticstack/issues/359
=> Edit alerting rule guide and resource descriptions

CHANGELOG.md, docs/index.md, docs/resources/kibana_action_connector.md, docs/resources/kibana_alerting_rule.md, docs/resources/kibana_space.md, examples/provider/kibana.tf, examples/provider/provider-env.tf, examples/resources/elasticstack_kibana_action_connector/resource.tf, examples/resources/elasticstack_kibana_alerting_rule/resource.tf, examples/resources/elasticstack_kibana_space/resource.tf, internal/clients/api_client.go, templates/index.md.tmpl
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/404
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/380
Does what it says on the tin. We already support configuring all Kibana attributes through environment variables. Added the missing Fleet attributes in and made sure they're all part of the docs.
=> Document all environment variables used within the provider. 

docs/resources/elasticsearch_component_template.md, examples/resources/elasticstack_elasticsearch_component_template/resource.tf
The template block expects an "aliases" block. However, this block is actually supposed to be named "alias".
Fixes #411
=> fix: update component documentation

CHANGELOG.md, internal/kibana/slo.go, internal/kibana/slo_test.go
Fixes a Kibana SLO panic due to incorrect field type on the Kibana SLO histogram_custom_indicator `to` and `from` fields.
Closes #429
=> Fix Kibana SLO panic `histogram_custom_indicator`

internal/clients/kibana/connector.go, internal/kibana/connector_test.go
Connectors were only properly storing url in the config in the tfstate file as they were being mapped to Tines. 
Fix #388
=> Fix mapping of webhook connectors that is stored in tfstate

internal/kibana/space.go, internal/kibana/space_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/345
Kibana spaces shouldn't need Elasticsearch to be configured to work.
=> Don't require elasticsearch for Kibana resources

internal/clients/kibana/slo.go
When creating the SLOs against a custom space ID, I'm getting the following errors:
```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to elasticstack_kibana_slo.kibana_http_latency_slo, provider "provider[\"terraform.local/elastic/elasticstack\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```
This is caused because TF is correctly creating it in the indicated space, but retrieving it from the `default` one.
=> Kibana SLOs: use `spaceID`

.buildkite/hooks/pre-command, .buildkite/release.yml, .buildkite/scripts/release.sh, .ci/pipelines/release.Jenkinsfile, .goreleaser.yml, Makefile, catalog-info.yaml
Fixes the release pipeline:
* uses the proper vault path (there was no value defined previously)
* fixes go version discrepancy
* limit parralelism to avoid build failure
* proper secrets handling
Note: atm, this is just running `make release-no-publish` until we can have the job run only on tag pushes.
=> Fix buildkite release pipeline

CHANGELOG.md, docs/resources/fleet_integration_policy.md, internal/fleet/integration_policy_resource.go
- Relaxed the requirement for input for Fleet integration policies.
- Certain integrations, such as the Elastic Agent integration, do not require any additional configuration, which means an input would not be provided.
Closes #486
=> Make input optional for Fleet integration policies

CHANGELOG.md, internal/fleet/integration_policy_resource.go, internal/fleet/shared_test.go
- When new inputs are read from the Fleet API, the list is sorted according to the existing plan. Any new inputs added from the API will be moved to the end of the list. This ensures a consistency of inputs and prevents unnecssary changes from appearing.
Closes #473
=> Sort Fleet integration policy inputs to ensure consistency

CHANGELOG.md, internal/kibana/alerting.go
`NilPointer` can happen if we try to read and update rules which have not been executed.
This PR protects the code in that scenario.
=> Do not set LastExecutionDate if it is `nil`

.buildkite/hooks/pre-command, .buildkite/scripts/release.sh
This change, related to https://github.com/elastic/ci/pull/2506 updates the release script to read the PGP keys from a more secured location shared with less folks. The GPG key information is now in a secured shared location accessible only to members of the GH group `terraform-providers-admins` and to the CI pipelines of this repository and terraform-provider-elasticstack.
Note - I also updated the pipeline to actual release the binary (it was set to `-no-publish` before).
Related change: https://github.com/elastic/terraform-provider-ec/pull/758
=> Secured release pipeline

CHANGELOG.md, internal/fleet/output_resource.go, internal/fleet/output_resource_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/506
Uses the returned output type rather than relying on internal state for parsing the response during read/import.
=> Populate all relevant attributes during fleet output import

CHANGELOG.md, docs/index.md, internal/clients/config/kibana.go, internal/clients/config/kibana_test.go, internal/clients/config/provider.go, internal/schema/connection.go
Fixes #368 
Adds a new optional `ca_certs` Parameter to the Kibana Configuration Block
=> Add Kibana CA Certs optional parameter

.github/ISSUE_TEMPLATE/bug_report.md
Just a reminder for anyone making bug requests not to leak secrets.
=> Add redaction reminder for base64 encoded credentials in debug output

CHANGELOG.md, internal/kibana/data_view/acc_test.go, internal/kibana/data_view/schema.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/548
Ensures that the override value is correctly persisted when managing data views
=> Persist override value during data view read

CHANGELOG.md, generated/data_views/README.md, generated/data_views/api/openapi.yaml, generated/data_views/api_data_views.go, generated/data_views/bundled.yaml, internal/clients/api_client.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/529
Does what it says on the tin, adds support for API key auth into the data view resource.
=> Support API Keys with data_view resource

CHANGELOG.md, docs/resources/elasticsearch_transform.md, docs/resources/kibana_security_role.md, examples/resources/elasticstack_elasticsearch_transform/import.sh, examples/resources/elasticstack_kibana_security_role/resource.tf
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/539
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/537
=> Fixup docs

CHANGELOG.md, internal/kibana/data_view/acc_test.go, internal/kibana/data_view/schema.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/547
=> Fixup JSON tags on field attribute model

CHANGELOG.md, docs/resources/elasticsearch_index_lifecycle.md, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/ilm_test.go
There is a parameter for the hot, warm and cold phases called downsample.
According to the description:
"Roll up documents within a fixed interval to a single summary document. Reduces the index footprint by storing time series data at reduced granularity."
As of 0.11.0 there is no support for this parameter in the proivider, this PR adds it.
=> Add downsample to ILMs

CHANGELOG.md, internal/clients/fleet/client.go
as this part of the documentation says https://www.elastic.co/guide/en/cloud/current/ec-api-authentication.html
=> feat: use ApiKey instead of Bearer

docs/resources/elasticsearch_index_lifecycle.md, internal/elasticsearch/index/ilm.go
👋🏽 The `set_priority` documentation was incorrect and was a bad copy-paste of the `shrink` documentation. 
https://www.elastic.co/guide/en/elasticsearch/reference/8.12/ilm-set-priority.html
> Phases allowed: hot, warm, cold.
>
> Sets the [priority](https://www.elastic.co/guide/en/elasticsearch/reference/8.12/recovery-prioritization.html) of the index as soon as the policy enters the hot, warm, or cold phase. Higher priority indices are recovered before indices with lower priorities following a node restart.
>
> Generally, indexes in the hot phase should have the highest value and indexes in the cold phase should have the lowest values. For example: 100 for the hot phase, 50 for the warm phase, and 0 for the cold phase. Indices that don’t set this value have a default priority of 1.
=> Updating `set_priority` documentation

.gitignore, CHANGELOG.md, Makefile, internal/clients/api_client.go, provider/provider_test.go
This ensures that logging and tls options are consistent across all Kibana endpoints. This mass of openapi clients is a huge pain, I wonder if it would be nicer to bundle the individual openapi specs together and have a single mass client 🤷 
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/582
=> Re-use the http client from the kibana client in the openapi generated clients

CHANGELOG.md, internal/elasticsearch/index/component_template.go, internal/elasticsearch/index/template.go, internal/elasticsearch/index/template_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/417
Adds a checked cast to catch the panic when the `template` block is nil. Also removes the duplicate code from the `component_template` resource to fix the same panic there.
=> Don't panic when the template is not defined

CHANGELOG.md, internal/models/models.go, internal/models/models_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/439
Elasticsearch supports both a string array (what the provider has been expecting) and a CSV list for the `indices` field on an SLM policy. This PR customises the JSON marshaller to ensure both formats are parsed into a Go slice.
=> Support CSV indices in SLM policy definitions

CHANGELOG.md, docs/resources/elasticsearch_index.md, internal/clients/api_client.go, internal/elasticsearch/index/index.go, internal/models/models.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/629
Updates the date parsing logic to support short form dates from Serverless projects. Also avoid some restrictions in managing indices in Serverless projects.
=> Don't crash when configuring Serverless projects. 

internal/fleet/agent_policy_resource.go, internal/fleet/integration_policy_resource.go
Populates policy_id when importing fleet policies and integrations.
This enables to update fleet policies in-place when using an import block.
Solves https://github.com/elastic/terraform-provider-elasticstack/issues/496
=> Populate policy_id when importing fleet policies and integrations

.github/workflows/test.yml, CHANGELOG.md, docs/resources/elasticsearch_index_lifecycle.md, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/ilm_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/661
=> Support allow_write_after_shrink in ILM policies

CHANGELOG.md, internal/fleet/fleet_server_host_resource.go, internal/fleet/fleet_server_host_resource_test.go, internal/fleet/output_resource.go, internal/fleet/output_resource_test.go
Currently the **output_id** setting is ignored in **elasticstack_fleet_output** as does the **host_id** for the **elasticstack_fleet_server_host** resource 
This is getting fixed with this pull request.
=> Fix setting ID for Fleet outputs and servers

libs/go-kibana-rest/docker-compose.yml, libs/go-kibana-rest/kbapi/api.kibana_spaces_test.go
I noticed that the docker-compose used for testing the Kibana rest client was broken (the Kibana password was not correctly set in ES).
I took the opportunity to upgrade the version.
Now we can run in `libs/go-kibana-rest`:
1. `docker-compose up -d`
2. `make test`
And they pass! 🎉
=> [libs/go-kibana-rest] Update docker-compose

CHANGELOG.md, internal/clients/fleet/fleet.go, internal/fleet/enrollment_tokens_data_source.go
The data source is not handling pagination at all. This fix the case when kibana server got more than 20 fleet enrollment tokens and the provider is not paginating the result when searching for a match.
Fetching all tokens case (empty policyID in input) is still not handled. Just trying to push a fix with minimum effort for now.
Partially fixes https://github.com/elastic/terraform-provider-elasticstack/issues/528.
=> Fix fleet_enrollment_tokens returning empty token set in some case

libs/go-kibana-rest/docker-compose.yml, libs/go-kibana-rest/go.mod, libs/go-kibana-rest/go.sum, libs/go-kibana-rest/kbapi/api._.go, libs/go-kibana-rest/kbapi/api.kibana_spaces_test.go, libs/go-kibana-rest/kbapi/api.kibana_synthetics.go, libs/go-kibana-rest/kbapi/api.kibana_synthetics_test.go, libs/go-kibana-rest/kbapi/api_test.go, libs/go-kibana-rest/kibana.yml
Related to https://github.com/elastic/terraform-provider-elasticstack/issues/610
This PR adds support for synthetic `http` Monitor and PrivateLocation APIs. 
Main doc: https://www.elastic.co/guide/en/kibana/current/synthetics-apis.html
Notes: 
1. new `uuid` dependency for testing purposes
2. proposed way to model monitor API. Different monitor kinds has different set of parameters. 
3. updated to `8.14.3`
4. added kibana config for docker compose
=> feat(synthetics): add synthetics monitor and private location API support to go-kibana-rest

CHANGELOG.md, docs/resources/elasticsearch_security_api_key.md, examples/resources/elasticstack_elasticsearch_security_api_key/resource.tf, internal/elasticsearch/security/api_key.go, internal/elasticsearch/security/api_key_test.go, internal/models/models.go
In its current form the provider is unable to provision API keys that have a restriction specified in the role descriptors.
For example, given this terraform:
```terraform
resource "elasticstack_elasticsearch_security_api_key" "api_key_with_restriction" {
name = "restricted-key"
role_descriptors = jsonencode({
role-a = {
indices = [
{
names      = ["index-a*"],
privileges = ["read"]
}
],
restriction = {
workflows = [ "search_application_query" ]
}
}
})
}
```
The provider will happily create an API key named `restricted-key` however the `restriction` field is not persisted in Elasticsearch.
On the next `terraform plan`, this API key will be marked as needing replacement due to the fact that the comparison between the local terraform definition and the response from the Elasicsearch API are …
=> Support `restriction` in `elasticstack_elasticsearch_security_api_key`

CHANGELOG.md, Makefile
In preparation for the release
=> Bump version for 0.11.5

.buildkite/hooks/pre-command, .buildkite/scripts/release.sh
The `VAULT_GITHUB_TOKEN` env var contains the token with permissions to create releases. Goreleaser on the other hand will only use `GITHUB_TOKEN` for the release.
=> Use ephemeral github token for build.

CHANGELOG.md, docs/resources/elasticsearch_component_template.md, docs/resources/elasticsearch_index_template.md, internal/elasticsearch/index/component_template.go, internal/elasticsearch/index/index.go, internal/elasticsearch/index/template.go, internal/elasticsearch/index/validation.go, internal/elasticsearch/index/validation_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/700
Validates that these attributes are specifically objects, hopefully pointing users to the correct place to look.
=> Validate that mappings are a JSON object, not just valid json

CHANGELOG.md, docs/resources/elasticsearch_index_template.md, internal/elasticsearch/index/commons.go, internal/elasticsearch/index/template.go, internal/models/models.go
=> add support for datastream lifecycle

CHANGELOG.md, internal/kibana/connector_data_source.go
Make sure that datasourceConnectorRead() returns the appropriate error when no connectors are found.
=> internal/kibana: fix datasourceConnectorRead error

CHANGELOG.md, internal/kibana/import_saved_objects/acc_test.go, internal/kibana/import_saved_objects/create.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/702
This PR:
* Updates the error model to fix the provider panic in the linked issue
* Updates the error handling to log a warning if the import was partially successful, and an error if no objects were imported
* Improves the error messaging to provide details on what failed to import
=> Fixup error handling during saved object imports

CHANGELOG.md, internal/elasticsearch/cluster/snapshot_repository_data_source.go, internal/elasticsearch/cluster/snapshot_repository_data_source_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/605
=> Prevent a provider panic when the referenced snapshot repo does not exist

CHANGELOG.md, internal/elasticsearch/security/api_key_test.go, internal/elasticsearch/security/role_test.go, internal/models/models.go
Solves #765 
- Add `remote_indices` to `models.ApiKeyRoleDescriptor`
- Add `allow_restricted_indices` to `models.RemoteIndexPerms`
- Updated existing test for a remote index entry.
=> update elasticsearch_security_api_key model/test

internal/clients/elasticsearch/index.go, internal/elasticsearch/index/index/acc_test.go, internal/elasticsearch/index/index/models.go, internal/elasticsearch/index/index/schema.go, internal/utils/planmodifiers/bool_default.go, internal/utils/planmodifiers/string_default.go
There's a fair bit of complexity around handling computed settings. I'll look at adding this back in a follow up PR, but want to get this resource in a working state so we can make a new release.
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/767
=> Don't populate settings during read

CHANGELOG.md, internal/clients/fleet/fleet.go, internal/fleet/agent_policy_resource.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/676
This attribute was being entirely ignored by the resource.
=> Apply the sys_monitoring attribute during creation

internal/elasticsearch/index/index/acc_test.go, internal/elasticsearch/index/index/schema.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/802
=> Allow mappings to be unknown to support mappings defined in index templates

docs/resources/kibana_data_view.md, internal/kibana/data_view/schema.go, internal/kibana/data_view/schema_test.go
This PR adds support for the `urlTemplate` and `labelTemplate` attributes when specifying a field in a Data View as type URL, as well as adding functionality to account for when any available `field_formats.params.attributes` don't exist.
By specifying that all fields in `apiFieldFormatParams` are optional, other custom field format types (colour, key/value, etc.) can be added much easier.
=> Add URL support to data_view field_formats

CHANGELOG.md, internal/fleet/integration_policy/create.go, internal/fleet/integration_policy/read.go, internal/fleet/integration_policy/secrets.go, internal/fleet/integration_policy/secrets_test.go, internal/fleet/integration_policy/update.go
I migrated work to 0.11.8, and any secret refs were removed in the state after apply.
During testing, it looked like responses either came in the format of 
```{"k1": "v1", ...}``` or ```{"k1": {"type": "string", "value": "v2"}, ...}```. Any time a secretRef was seen, it was inside the latter format. Apparently they can also show up in the former. This fixes the oversight, unit test didn't catch it :(
=> fix package policy secrets

CHANGELOG.md, docs/resources/elasticsearch_security_role.md, examples/resources/elasticstack_elasticsearch_security_role/resource.tf, internal/elasticsearch/security/role.go, internal/elasticsearch/security/role_test.go, internal/models/models.go
Adds the "description" attribute to elasticstack_elasticsearch_security_role resource.
Should resolve #822
=> Add description to security_role resource

CHANGELOG.md, internal/fleet/output/schema.go
Fixes #840 
Add default: False to default_integrations and default_monitoring.
This was not found by the tests because both fields are set in each test.
=> Fix output inconsistent result (default_integrations/monitoring)

CHANGELOG.md, internal/elasticsearch/index/indices/models.go
Hello,
A little fix on the elastic indices datasource. When parsing boolean settings the following error could occur:
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: failed to convert setting to bool
│ 
│   with data.elasticstack_elasticsearch_indices.existing_indices["my-indice"],
│   on main.tf line 56, in data "elasticstack_elasticsearch_indices" "existing_indices":
│   56: data "elasticstack_elasticsearch_indices" "existing_indices" {
│ 
│ expected setting to be a bool but got %!t(string=false)
```
@tobio I think a fast review could let it be included in the 0.11.9 version.
Thanks.
=> fix: elastic indices datasource boolean parsing

CHANGELOG.md, internal/fleet/integration_policy/resource_test.go, internal/kibana/alerting.go, internal/kibana/alerting_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/829
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/770
Updates validation to check attributes are Elastic durations, not Golang durations.
=> Alerting fields should be Elastic durations, not Golang durations

CHANGELOG.md, internal/clients/kibana/alerting.go, internal/kibana/alerting_test.go
Fixes https://github.com/elastic/kibana/issues/196797
The `alert_delay` field was being created properly but not updated.
=> Fix `alert_delay` update in Update Rule API

CHANGELOG.md, internal/fleet/enrollment_tokens/models.go, internal/fleet/integration/create.go, internal/fleet/integration/update.go, internal/fleet/integration_policy/models.go, internal/fleet/integration_policy/resource.go, internal/fleet/integration_policy/schema.go, internal/fleet/integration_policy/upgrade.go, internal/fleet/output/models.go, internal/fleet/server_host/models.go, internal/kibana/synthetics/schema.go, internal/utils/tfsdk.go, internal/utils/tfsdk_test.go
As mentioned [here](https://github.com/elastic/terraform-provider-elasticstack/pull/854#issuecomment-2419856734), the idea behind the utils/tfsdk.go meta parameters is to pass around response.Diagnostics, the key/index, path, etc. Anything added to meta.diags doesn't actually get returned because it is passed by value and not pointer. This never cropped up in the other tests, mostly because the tests pass, but secondly all the usage is inline, so they reference the outer diags, and not meta.diags.
=> update tfsdk helpers to use *diags

CHANGELOG.md, internal/clients/elasticsearch/security.go, internal/elasticsearch/security/api_key/acc_test.go, internal/elasticsearch/security/api_key/resource.go, internal/elasticsearch/security/api_key/schema.go, internal/elasticsearch/security/api_key/state_upgrade.go
SDK based api_key resources stored `expiration:""` in state when it's unset in config, however PF based resources more specifically model this as `null`. This is causing TF to force the replacement of API Keys when upgrading from 0.11.10.
This PR updates the RequiresReplace logic to only require replacement when the expiration value actually changes (e.g `1d` -> `null`). It also adds an acceptance test verifying provider behaviour during the migration from SDK->PF, specifically that the underlying API Key is not replaced. 
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/873
=> Don't force resource replacement when expiration is unset during SDK-PF migration

CHANGELOG.md, docs/data-sources/elasticsearch_security_role.md, internal/elasticsearch/security/role_data_source.go, internal/elasticsearch/security/role_data_source_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/880
=> Support description in the role data source

CHANGELOG.md, internal/clients/kibana/alerting.go, internal/clients/kibana/alerting_test.go, internal/kibana/alerting.go, internal/kibana/alerting_test.go, internal/models/alert_rule.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/874
Ensure that KQL and Timeframe fields are only populated if they're actually set in the TF module.
=> Support alerting rules with only one of kql or timeframe fields

internal/clients/api_client.go
I found these missing debug configuration while working on a Crossplane provider and on #948.
With this PR, HTTP requests and responses are written on the standard output for SLO and saved objects.
=> Additional debug flag on HTTP clients

CHANGELOG.md, internal/fleet/integration_policy/secrets.go
Fixes #907 
Before:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10143df80]
```
After:
```
```
=> integration policy: handle NPE in secrets 

.github/workflows/test.yml, CONTRIBUTING.md, Makefile, internal/clients/elasticsearch/index.go, internal/fleet/integration_policy/resource_test.go, internal/kibana/role.go, libs/go-kibana-rest/CONTRIBUTING.md, libs/go-kibana-rest/docker-compose.yml, libs/go-kibana-rest/kbapi/api.kibana_role_management.go, libs/go-kibana-rest/kbapi/api.kibana_spaces_test.go, libs/go-kibana-rest/kbapi/api.kibana_synthetics_test.go
=> chore: add support 8.16.2 to go-kibana-rest and acc tests

catalog-info.yaml
The `control-plane-stateful-applications` team was renamed to `control-plane-hosted-applications`. This change needs to be reflected in this `catalog-info.yaml` as well.
=> fix: update team name - control-plane-hosted-applications

internal/acctest/acctest.go
The current acceptance setup code was not allowing me to use an API key even if it's now supported by Kibana.
This PR makes it to use api keys to run acceptance tests.
I didn't run the full acceptance test suite with this. Acceptance is passing for #948 with an API key.
=> Accept API keys for running acceptance tests

CHANGELOG.md, docs/resources/elasticsearch_index_lifecycle.md, internal/elasticsearch/index/data_stream_test.go, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/ilm_test.go
* Add `max_primary_shard_docs` condition to rollover (closes  #794)
* Update test for rollover `max_primary_shard_docs` condition
* Specify min version in the description
* Update CHANGELOG.md
=> Add `max_primary_shard_docs` condition to ILM rollover

CHANGELOG.md, internal/kibana/data_view/models.go, internal/kibana/data_view/models_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/975
Basically restores the old implementation for [this function](https://github.com/elastic/terraform-provider-elasticstack/pull/881/files#diff-6ee1b4568dae9bbeea095558f5ebfd094ba702a77d3eda1e3a5f90f385def37dL278-L288). A previous provider version didn't include the composite ID and so we need to continue support. We could in theory write a state migration but that's a lot more work.
=> Restore support for non-composite data view ids

CHANGELOG.md, internal/kibana/data_view/create.go, internal/kibana/data_view/models.go, internal/kibana/data_view/models_test.go, internal/kibana/data_view/read.go, internal/kibana/data_view/update.go
Fixes #1005 
I should have commented why I added the SpaceID to the list of namespaces the first time. 
When creating a dataview, if the target namespace (`/s/<ns>`) is not included in the `dataview.namespaces` field, when attempting to GET the object afterwards a 404 is received. So the SpaceID or default space is always required to be present, however an additional check to ignore if missing from the namespaces field should be added.
=> Fix dataview namespaces regression

internal/clients/api_client.go, internal/fleet/agent_policy/update.go
Fixes two issues that lead to confusing errors being shown:
- The `agent_policy` resource did not throw an error if getting the stack version fails
- When getting the stack version fails, it only returned the http connection error, not actually stating what it was trying to do.
In combination this will now lead to an error like
> `Error: failed to get version from Kibana API: Get "http://localhost:5601/api/status": dial tcp [::1]:5601: connect: connection refused,  Please ensure a working 'kibana' endpoint is configured.`
=> Improve error messaging if no Kibana endpoint is configured.

CHANGELOG.md, docs/resources/elasticsearch_snapshot_repository.md, internal/elasticsearch/cluster/snapshot_repository.go
This PR introduces support for specifying a custom endpoint in the S3-based snapshot repository configuration. It allows users to define a custom S3-compatible storage endpoint instead of relying solely on AWS defaults.
✅ Changes
- Added support for endpoint configuration in snapshot repository settings.
- Enables use of custom or on-prem S3-compatible storage services.
🔧 Use Case
Useful for setups involving:
- MinIO or other S3-compatible backends
- VPC endpoints
🔗 Related Issue
Potentially fixes #1096
=> Support for custom endpoint configuration in snapshot repository setup

CONTRIBUTING.md, generated/kbapi/README.md, generated/kbapi/transform_schema.go
Trying to make this mess a little less messy.
=> Add basic docs around the current kbapi generation

CHANGELOG.md, docs/resources/kibana_slo.md, internal/kibana/slo.go, internal/kibana/slo_test.go
fix https://github.com/elastic/terraform-provider-elasticstack/issues/1144
I've implemented client-side validation for the `slo_id` field in the Kibana SLO resource to prevent invalid values from reaching the API and causing confusing 400 errors.
Previously, the `slo_id` field lacked validation on the provider side, allowing invalid values like "supdawg" (only 7 characters) to pass through to the Kibana API. This resulted in unhelpful 400 Bad Request errors from the server instead of clear validation feedback at plan time.
As mentioned in the GitHub issue \#1144, users (me!) currently experience:
- Short IDs (\< 8 characters) accepted by Terraform but rejected by the API  
- Unclear error messages when invalid characters are used  
- Poor user experience with late-stage failures during …
=> Adds validation for slo_id

CONTRIBUTING.md, README.md
Add some more detailed instructions on how to write code for the provider. This is more of a starting point which can be extended further. The goal is to have a basic guidance for anyone new to the provider development: Which plugin to use, which resource to use as a baseline example, etc.
=> Extend CONTRIBUTING.md

CHANGELOG.md, docs/resources/kibana_slo.md, internal/kibana/slo.go, internal/kibana/slo_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/1070
Docs for this option are here: https://www.elastic.co/docs/api/doc/serverless/operation/operation-createsloop#operation-createsloop-body-application-json-settings-preventinitialbackfill
I've not done any Terraform additions like this one, so there is a good chance the syntax here is wrong — I see that this new setting likely needs to be added in a few additional places to make use of it after it's been added to the schema, so I'd appreciate guidance on where that needs to happen, exactly. 
At any rate, it would be great to add this field, and as it's a new, optional field, it shouldn't have any breaking change consequences whatsoever.
UPDATE: I re-generated the SLO model files with openapi-generator, hoping it …
=> Add optional preventInitialBackfill for SLO API
