elastic/terraform-provider-elasticstack

CHANGELOG.md, Makefile
This adds proper CHANGELOG file
=> Add CHANGELOG.md file

CHANGELOG.md, docs/resources/elasticsearch_index.md, examples/resources/elasticstack_elasticsearch_index/resource.tf, internal/elasticsearch/index/index.go
This change will allow to manage dynamic index settings, and update them anytime. 
fix https://github.com/elastic/terraform-provider-elasticstack/issues/52
=> Update only changed index settings

docs/guides/elasticstack-and-cloud.md, examples/cloud/provider.tf, templates/guides/elasticstack-and-cloud.md.tmpl
Just to make sure all the things work together.
=> Fix the guide to make it work with the current provider version

CHANGELOG.md, internal/models/models.go
fix https://github.com/elastic/terraform-provider-elasticstack/issues/78
=> Fix spelling in index alias model

CHANGELOG.md, docs/resources/elasticsearch_index_lifecycle.md, examples/resources/elasticstack_elasticsearch_index_lifecycle/resource.tf, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/ilm_test.go
fix: https://github.com/elastic/terraform-provider-elasticstack/issues/80
=> Properly handle number_of_replicas in allocate action in ILM

CHANGELOG.md, internal/elasticsearch/index/ilm.go
fix: https://github.com/elastic/terraform-provider-elasticstack/issues/87
=> Set ILM name on read

CHANGELOG.md, docs/resources/elasticsearch_index_lifecycle.md, examples/resources/elasticstack_elasticsearch_index_lifecycle/resource.tf, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/ilm_test.go
fix https://github.com/elastic/terraform-provider-elasticstack/issues/88
=> Fix set priority in ILM template

CHANGELOG.md, internal/clients/security.go
fixes https://github.com/elastic/terraform-provider-elasticstack/issues/101
=> Correctly identify a missing security user

.github/CODEOWNERS
I'm not the code owner here anymore
=> Remove myself as a code owner from this repo

CHANGELOG.md, internal/clients/cluster.go, internal/elasticsearch/cluster/snapshot_repository.go, internal/elasticsearch/cluster/snapshot_repository_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/116
=> Set the snapshot repo name during read

internal/elasticsearch/cluster/script_test.go, internal/elasticsearch/cluster/settings_test.go, internal/elasticsearch/cluster/slm_test.go, internal/elasticsearch/cluster/snapshot_repository_test.go, internal/elasticsearch/index/component_template_test.go, internal/elasticsearch/index/data_stream_test.go, internal/elasticsearch/index/ilm_test.go, internal/elasticsearch/index/template_test.go, internal/elasticsearch/ingest/pipeline_test.go, internal/elasticsearch/security/role_test.go, internal/elasticsearch/security/user_test.go
=> Fix to use resource.Test for acceptance tests

.ci/Makefile.ci, .ci/jobs/elastic+terraform-provider-elasticstack+tag.yml, .ci/pipelines/release.Jenkinsfile, .github/workflows/test.yml, Makefile, scripts/retry.sh
Largely copied from the https://github.com/elastic/terraform-provider-ec pipeline. 
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/157
=> Add Jenkins release job

docs/resources/elasticsearch_security_api_key.md, examples/resources/elasticstack_elasticsearch_security_api_key/resource.tf, internal/elasticsearch/security/api_key.go
=> Add sensitive to api_key and encoded fields in api key resource

internal/elasticsearch/security/api_key.go, internal/elasticsearch/security/api_key_test.go, internal/versionutils/testutils.go, provider/provider_test.go
=> Add tests with api_key connection

provider/provider_test.go
Related to https://github.com/elastic/terraform-provider-elasticstack/pull/197
=> Set allow_restricted_indices in api key es connection test

internal/elasticsearch/index/ilm_test.go
Found a place to utilise the recently added version utility
=> Utilise new version util

internal/clients/elasticsearch/index.go, internal/elasticsearch/index/component_template.go, internal/elasticsearch/index/data_stream.go, internal/elasticsearch/index/ilm.go, internal/elasticsearch/index/index.go, internal/elasticsearch/index/template.go, internal/elasticsearch/ingest/pipeline.go
Related to https://github.com/elastic/terraform-provider-elasticstack/issues/100
Some more cleanup prior to introducing Kibana
=> Refactor elasticsearch index client methods

internal/clients/elasticsearch/logstash.go, internal/elasticsearch/logstash/pipeline.go
Related to https://github.com/elastic/terraform-provider-elasticstack/issues/100
Some more cleanup prior to introducing Kibana
=> Refactor elasticsearch logstash client methods

internal/clients/elasticsearch/security.go, internal/elasticsearch/security/api_key.go, internal/elasticsearch/security/api_key_test.go, internal/elasticsearch/security/role.go, internal/elasticsearch/security/role_mapping.go, internal/elasticsearch/security/system_user.go, internal/elasticsearch/security/user.go, internal/elasticsearch/security/user_data_source.go
Related to https://github.com/elastic/terraform-provider-elasticstack/issues/100
Some more cleanup prior to introducing Kibana
=> Refactor elasticsearch security client methods

CHANGELOG.md
Forgot to get this added in the PR like a schmuck
=> Update changelog for client certificate authentication

CHANGELOG.md, Makefile, README.md, docs/guides/elasticstack-and-cloud.md, examples/cloud/provider.tf
Bumping versions for 0.5.0 inline with https://github.com/elastic/terraform-provider-elasticstack/pull/146
=> Bump versions for 0.5.0

CHANGELOG.md
Rookie mistake forgetting this...
=> Update changelog for API client refactor

internal/elasticsearch/index/index.go, internal/elasticsearch/index/index_test.go
Separate mapping diff function and add tests for it
=> Add tests to mapping diff check

CHANGELOG.md, docs/resources/elasticsearch_index.md, internal/elasticsearch/index/index.go, internal/elasticsearch/index/index_test.go
=> Add `mapping_coerce` field to index resource

internal/kibana/alerting.go, internal/kibana/alerting_test.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/298
Messed this up since I was hoping the acceptance test would create a connector to use. Total #testingfail here.
=> Fixup transforming actions to/from the TF resource data

CHANGELOG.md, docs/resources/elasticsearch_logstash_pipeline.md, internal/elasticsearch/logstash/pipeline.go, internal/elasticsearch/logstash/pipeline_test.go
COB-3434: Updated queue.max_bytes with unsupported number and units
=> COB-3434: Updated queue.max_bytes with unsupported number and units

CHANGELOG.md, internal/clients/api_client.go, internal/clients/fleet/client.go, internal/utils/http_log.go
Enable HTTP logging for Kibana action connectors client.
=> HTTP logging for Kibana action connectors

docs/resources/kibana_security_role.md, examples/resources/elasticstack_kibana_security_role/resource-with-base.tf, examples/resources/elasticstack_kibana_security_role/resource-with-feature.tf, internal/kibana/role.go, templates/resources/kibana_security_role.md.tmpl
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/586
=> Kibana role docs

CHANGELOG.md, internal/kibana/data_view/schema.go
=> Fix: Panic on `elasticstack_kibana_data_view` when `pattern` is not defined

internal/clients/kibana/alerting_test.go, internal/clients/kibana/common.go
Not sure when this got introduced but it's identical to `utils.Pointer`
=> Remove duplicate code

internal/elasticsearch/index/index/acc_test.go, internal/elasticsearch/index/index/resource.go, internal/elasticsearch/index/index/schema.go
=> Support imports on plugin framework index

docs/resources/elasticsearch_security_user.md, examples/resources/elasticstack_elasticsearch_security_user/import.sh
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/866
=> Indicate the username is variable

CHANGELOG.md, internal/fleet/agent_policy/resource_test.go, internal/fleet/agent_policy/schema.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/839
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/831
=> UseStateForUnknown for agent policy ids

docs/data-sources/elasticsearch_index_template.md, docs/data-sources/elasticsearch_security_role.md, docs/data-sources/elasticsearch_security_role_mapping.md, docs/data-sources/elasticsearch_security_user.md, docs/data-sources/elasticsearch_snapshot_repository.md, docs/index.md, docs/resources/elasticsearch_cluster_settings.md, docs/resources/elasticsearch_component_template.md, docs/resources/elasticsearch_data_stream.md, docs/resources/elasticsearch_data_stream_lifecycle.md, docs/resources/elasticsearch_enrich_policy.md, docs/resources/elasticsearch_index.md, docs/resources/elasticsearch_index_lifecycle.md, docs/resources/elasticsearch_index_template.md, docs/resources/elasticsearch_ingest_pipeline.md, docs/resources/elasticsearch_logstash_pipeline.md, docs/resources/elasticsearch_script.md, docs/resources/elasticsearch_security_api_key.md, docs/resources/elasticsearch_security_role.md, docs/resources/elasticsearch_security_role_mapping.md, docs/resources/elasticsearch_security_system_user.md, docs/resources/elasticsearch_security_user.md, docs/resources/elasticsearch_snapshot_lifecycle.md, docs/resources/elasticsearch_snapshot_repository.md, internal/schema/connection.go
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/956
@Leaf-Lin is this the change you're after (you can just look at the first commit)? Otherwise, want to let me know what you'd like this to say?
=> Update es_client_authentication description

CHANGELOG.md, Makefile
Small patch release for this PR: https://github.com/elastic/terraform-provider-elasticstack/pull/1044
=> Prepare release 0.11.15

generated/kbapi/kibana.gen.go, generated/kbapi/transform_schema.go
Keeping this up to date to simplify things for new development. 
This omitempty thing is kind of annoying, we need to do something better here.
=> Regenerate Kibana client

internal/clients/api_client.go
Users shouldn't have to configure an Elasticsearch endpoint just to check the server flavor being used.
=> Support getting flavor from Kibana

docs/resources/elasticsearch_data_stream_lifecycle.md, templates/resources/elasticsearch_data_stream_lifecycle.md.tmpl
Fixes https://github.com/elastic/terraform-provider-elasticstack/issues/1230
=> Fix copy pasta in datastream lifecycle docs
